// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var ReactGridDnd = require("react-grid-dnd");

function initialState(param) {
  return /* array */[
          /* record */[
            /* id */1,
            /* name */"ben"
          ],
          /* record */[
            /* id */2,
            /* name */"joe"
          ],
          /* record */[
            /* id */3,
            /* name */"jason"
          ],
          /* record */[
            /* id */4,
            /* name */"chris"
          ],
          /* record */[
            /* id */5,
            /* name */"heather"
          ],
          /* record */[
            /* id */6,
            /* name */"Richard"
          ]
        ];
}

function Example(Props) {
  var match = React.useState((function () {
          return initialState(/* () */0);
        }));
  var setItems = match[1];
  var items = match[0];
  var onChange = function (sourceId, sourceIndex, targetIndex, targetId) {
    var result = ReactGridDnd.swap(items, sourceIndex, targetIndex);
    return Curry._1(setItems, (function (param) {
                  return result;
                }));
  };
  return React.createElement(ReactGridDnd.GridContextProvider, {
              onChange: onChange,
              children: React.createElement("div", {
                    className: "container"
                  }, React.createElement(ReactGridDnd.GridDropZone, {
                        className: "dropzone left",
                        boxesPerRow: 4,
                        rowHeight: 70,
                        id: "left",
                        children: Belt_Array.map(items, (function (item) {
                                var arg = item[/* name */1];
                                return React.createElement(ReactGridDnd.GridItem, {
                                            children: React.createElement("div", {
                                                  className: "grid-item"
                                                }, React.createElement("div", {
                                                      className: "grid-item-content"
                                                    }, (function (param) {
                                                              return (function (param$1) {
                                                                  return arg.slice(param, param$1);
                                                                });
                                                            })(0)(1).toLowerCase())),
                                            key: String(item[/* id */0])
                                          });
                              }))
                      }))
            });
}

var make = Example;

exports.initialState = initialState;
exports.make = make;
/* react Not a pure module */
